map_type: costmap

obstacle_range: 1.2 # 2.0 # 1.0=original Udacity # 2.0
raytrace_range: 2.0 # 4.0 # 2.0=original Udacity # 3.0

transform_tolerance: 0.25 # 0.1 # 0.2=original Udacity # 0.0 # Time with which to post-date the transform that is published, to indicate that this transform is valid into the future, default: 0.1 seconds

# Observed values from: http://wiki.ros.org/navigation/Tutorials/RobotSetup#Robot_Setup
robot_radius:        0.283  # my_robot, box size=".4 .2 .2" # Udacity=0.3 # note: note: radius not diameter
inflation_radius:    0.65 # 0.65 # 0.55 # 1.75 # 1.75 # 0.65 # 0.5=original Udacity # 0.0 # 0.2
cost_scaling_factor: 3.0 # 3.5 # 2.58 # 5.0 # 10.0 # 5.0=original Udacity

observation_sources: laser_scan_sensor

# laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /my_robot/laser/scan, marking: true, clearing: true}
# Atualizado em 15.02.2021 - 'my_robot.gazebo' file makes reference to: "<topicName>/scan</topicName>"
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# Ref.: http://wiki.ros.org/global_planner
visualize_potential: true # Specifies whether or not to visualize the potential area computed via a PointCloud2. default: false
cost_factor: 0.8 # 1.0 # Factor to multiply each cost from costmap by (dynamic reconfigure), default: 3.
